{
  "comments": [
    {
      "key": {
        "uuid": "PvHUk0mM",
        "filename": "src/com/android/providers/telephony/TelephonyProvider.java",
        "patchSetId": 3
      },
      "lineNbr": 325,
      "author": {
        "id": 1001401
      },
      "writtenOn": "2013-02-11T18:40:36Z",
      "side": 1,
      "message": "We talked about this internally and if the apn database is incorrect we want it to \"fail fast\". Therefore we think the following might be better:\n\n  while(parser.getEventType !\u003d XmlPullParser.END_DOCUMENT) {\n    XmuUtils.nextElement(parser);\n    ContentValues row \u003d getRow(parser);\n    if (row \u003d\u003d null) {\n      throw new XmlPullParserException(\"Expected \u0027apn\u0027 tag\", parser, null);\n    }\n    insertAddingDefaults(db, CARRIERS_TABLE, row);\n  }\n\nIf we agree on this \"fail fast\" mode, we\u0027ll probably want to throw the exception in getRow.",
      "revId": "0dab9f5e6e6c991891cc2d6f64b78fb4f10f46a9",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "PzTXacHM",
        "filename": "src/com/android/providers/telephony/TelephonyProvider.java",
        "patchSetId": 3
      },
      "lineNbr": 325,
      "author": {
        "id": 1016953
      },
      "writtenOn": "2013-02-12T01:42:21Z",
      "side": 1,
      "message": "I\u0027ve verified above code. There is a big problem. For the last line, \u003c/apns\u003e, it throws exception, so it doesn\u0027t work for normal xml.",
      "parentUuid": "PvHUk0mM",
      "revId": "0dab9f5e6e6c991891cc2d6f64b78fb4f10f46a9",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "PzZiB.V4",
        "filename": "src/com/android/providers/telephony/TelephonyProvider.java",
        "patchSetId": 3
      },
      "lineNbr": 325,
      "author": {
        "id": 1016953
      },
      "writtenOn": "2013-02-12T06:44:37Z",
      "side": 1,
      "message": "First of all, it occurs exception for \u003c/apns\u003e because of returning null in getRow(). If use continue, instead of \"throw...\", it\u0027ll be solved.\n\nAnyway, previous code was already \"fail fast\" mode. I wanted \"fault-tolerant\" for this. If it occurs exception due to malformed XML elements during making DB, user can not use proper APN or can not use DB. As using transaction, we get the fast time to make DB, but in exception situation, all data is rolled back. It means telephony.db is created, but there is no data in DB, just empty DB. To making up it\u0027s fault, I\u0027ve uploaded this patch.",
      "parentUuid": "PzTXacHM",
      "revId": "0dab9f5e6e6c991891cc2d6f64b78fb4f10f46a9",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "Py-SZESs",
        "filename": "src/com/android/providers/telephony/TelephonyProvider.java",
        "patchSetId": 3
      },
      "lineNbr": 325,
      "author": {
        "id": 1001401
      },
      "writtenOn": "2013-02-13T16:44:44Z",
      "side": 1,
      "message": "Our thinking is that we want it to fail on any error and not to be tolerant at all as this could mask the problem because it works most/some of the time.\n\nWhy do you want it to be tolerant?",
      "parentUuid": "PzZiB.V4",
      "revId": "0dab9f5e6e6c991891cc2d6f64b78fb4f10f46a9",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "P5D7tCec",
        "filename": "src/com/android/providers/telephony/TelephonyProvider.java",
        "patchSetId": 3
      },
      "lineNbr": 325,
      "author": {
        "id": 1016953
      },
      "writtenOn": "2013-02-14T07:13:44Z",
      "side": 1,
      "message": "Generally, there is no problme and currently, built apns-conf.xml is not malformed.\n\nHowerver, if user makes malformed apns-conf.xml and changes that of /system/etc \"CACLULATEDLY\", telephony.db is made as empty.\n\n1. wipe userdata and change apns-conf.xml on /system/etc/\n\n2. reboot\n\n3. Settings -\u003e Mobile Networks -\u003e Access Point Names \n\n4. maybe show \"Unfortunately, Settings has stopped\" message and stop Setting app.\n\nTo fix it, I think two approaches. One is this patch, the other is changing Settings Apps \nThis patch is,  in case of malform xml elements, just skip it, not stop.\n\nIf you don\u0027t want to be tolerant, what do you think of trying to change Setting Apps for exception situation. \n\nI\u0027ve uploaded related patch: https://android-review.googlesource.com/51710",
      "parentUuid": "Py-SZESs",
      "revId": "0dab9f5e6e6c991891cc2d6f64b78fb4f10f46a9",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}